N=100
S=1
noise=0.2
data=COVID
r=100
CUDA_VISIBLE_DEVICES=3 python runC.py --n_clients 2 --dataset $data --model ResNet9 --feature_dim 200 --rounds $r --seed $S --preset IL --data_size $N --noise $noise
CUDA_VISIBLE_DEVICES=3 python runC.py --n_clients 2 --dataset $data --model ResNet9 --feature_dim 200 --rounds $r --seed $S --preset CL --data_size $N --noise $noise
CUDA_VISIBLE_DEVICES=3 python runC.py --n_clients 2 --dataset $data --model ResNet9 --feature_dim 200 --rounds $r --seed $S --preset FD --data_size $N --noise $noise
CUDA_VISIBLE_DEVICES=3 python runC.py --n_clients 2 --dataset $data --model ResNet9 --feature_dim 200 --rounds $r --seed $S --preset FL --data_size $N --noise $noise
